
image: alpine:latest

stages:
  - test

before_script:
  - wget -nv https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
  - tar xvJf shellcheck-stable.linux.x86_64.tar.xz
  - cp shellcheck-stable/shellcheck /usr/local/bin

tests:
  stage: test
  script:
    - cd test && ./test.sh

