

stages:
  - test

codequality:
  stage: test
  image: alpine:latest
  before_script:
    - wget -nv https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
    - tar xvJf shellcheck-stable.linux.x86_64.tar.xz
    - cp shellcheck-stable/shellcheck /usr/local/bin
  script:
    - shellcheck lecert
    - shellcheck test/test.sh

tests:
  stage: test
  image: centos:latest
  script:
    - cd test && bash -x ./test.sh

